api_platform:
    title: GraphQL API Platform
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        multipart: ['multipart/form-data']
    graphql:
        enabled: true
        graphiql:
            enabled: true # Enables the browser-based IDE
        graphql_playground:
            enabled: false # Optional alternative IDE


