api_platform:
    graphql:
        enabled: true
        graphiql:
            enabled: true # Enables the browser-based IDE
        graphql_playground:
            enabled: false # Optional alternative IDE


# api_platform:
#     title: Hello API Platform
#     version: 1.0.0
#     graphql:
#         enabled: true
#         graphiql: { enabled: true }
#     defaults:
#         stateless: true
#         cache_headers:
#             vary: ['Content-Type', 'Authorization', 'Origin']

