<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260306033526 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category VARCHAR(255) DEFAULT NULL, descriptions VARCHAR(255) NOT NULL, qty INT DEFAULT 0 NOT NULL, unit VARCHAR(255) DEFAULT NULL, costprice NUMERIC(10, 2) DEFAULT 0 NOT NULL, sellprice NUMERIC(10, 2) DEFAULT 0 NOT NULL, saleprice NUMERIC(10, 2) DEFAULT 0 NOT NULL, productpicture VARCHAR(255) DEFAULT NULL, alertstocks INT DEFAULT 0 NOT NULL, criticalstocks INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D34A04ADC96EAEB6 ON product (descriptions)');
        $this->addSql('CREATE TABLE sale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, saleamount NUMERIC(10, 2) DEFAULT 0 NOT NULL, saledate TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, firstname VARCHAR(20) DEFAULT NULL, lastname VARCHAR(20) DEFAULT NULL, email VARCHAR(180) NOT NULL, mobile VARCHAR(15) DEFAULT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, roles JSON NOT NULL, isactivated INT DEFAULT 1 NOT NULL, isblocked INT DEFAULT 0 NOT NULL, secretkey TEXT DEFAULT NULL, mailtoken INT DEFAULT 0 NOT NULL, qrcodeurl TEXT DEFAULT NULL, userpic VARCHAR(10) DEFAULT \'pix.png\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, totp_secret VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE product');
        $this->addSql('DROP TABLE sale');
        $this->addSql('DROP TABLE "user"');
    }
}
