import 'bootstrap/dist/css/bootstrap.min.css';
import type { Metadata } from "next";
import Header from './layout/header';
import "./globals.css";
import BootstrapClient from './components/BootstrapClient';


export const metadata: Metadata = {
  title: "Supercar Inc.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header/>
        {children}
        <BootstrapClient/>
      </body>
    </html>
  );
}
